layout: {qmk_keyboard: crkbd/rev1, layout_name: LAYOUT_split_3x6_3}
layers:
  L0:
  - [Gui+SPC, Q, W, E, R, T, Y, U, I, O]
  - [P, TG( MEDIA), TAB, A, S, D, F, G, H, J]
  - [K, L, ;, '''', TD(TD SHIFT CAPS), Z, X, C, V, B]
  - [N, M, ',', ., /, \, SPC, LGUI, MO( NUM), TG( POWER)]
  - [ENT, BSPC]
  L1:
  - [ESC, '1', '2', '3', '4', '5', '6', '7', '8', '9']
  - ['0', DEL, Gui+`, '', '', '', '=', '-', '', LEFT]
  - [UP, RIGHT, '', '', TD(TD SHIFT CAPS), '', '', '', '[', ']']
  - ['', '', DOWN, '', '', '', Ctl+LOPT, LGUI, '', LCTL]
  - [ENT, LOPT]
  L2:
  - [OPTION CMD LBRACKET, OPTION CMD RBRACKET, '', '', '', '', '', MS BTN1, MS BTN2, '']
  - ['', Ctl+Gui+Q, C S RIGHT, CMD SHIFT BS, '', '', '', '', '', MS LEFT]
  - [MS UP, MS RIGHT, '', '', CMD P, CMD SHIFT P, OPTION CMD SLSH, Ctl+C, '', Gui+Sft+SPC]
  - ['', '', MS DOWN, '', '', '', Gui+SPC, Alt+LEFT GUI, '', TG( POWER)]
  - ['', '']
  L3:
  - [Alt+SPC, '', '', '', '', '', '', '', '', '']
  - ['', TG( MEDIA), '', '', MPRV, MPLY, MNXT, VOLU, '', '']
  - ['', '', '', '', TD(TD SHIFT CAPS), '', '', '', '', VOLD]
  - ['', '', '', '', \, ']', OLED ANIM, LCTL, '', MO( SETTINGS)]
  - ['', '']
  L4:
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', RGB TOG, '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '', '', '', '', '', '', '', '', '']
  - ['', '']
