name: Build QMK Firmware

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build QMK Firmware
        uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev1
          keymap: feynman
          controller: helios
          local-keymap-path: keymaps/corne/feynman

      - uses: actions/upload-artifact@v4
        with:
          name: built-images
          path: qmk-output

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: qmk-output/**
          tag_name: Latest
          name: Release latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
