name: Build my QMK configuration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Draw Keymap
        uses: ./.github/actions/keymap-drawer

      - name: Commit Keymap Config and Keymap Draw
        uses: stefanzweifel/git-auto-commit-action@v5

      # - uses: d3adb5/build-qmk-fw@v1
      #   with:
      #     keyboard: crkbd/rev1
      #     keymap: feynman
      #     controller: helios
      #     local-keymap-path: keymaps/corne/feynman

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: built-images
      #     path: qmk-output
