name: PR Workflow

on:
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  build-qmk:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Draw Keymap
        uses: ./.github/actions/keymap-drawer

      - name: Commit Keymap Config and Keymap Draw
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update keymap config and keymap draw

      - name: Build QMK Firmware
        uses: d3adb5/build-qmk-fw@v1
        with:
          keyboard: crkbd/rev1
          keymap: feynman
          controller: helios
          local-keymap-path: keymaps/corne/feynman

      - name: Upload Built Image
        uses: actions/upload-artifact@v4
        with:
          name: built-image
          path: qmk-output
